# Generated by Django 3.2.9 on 2021-11-24 11:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('Django', '.django'), ('Python', '.py'), ('Javascript', '.js'), ('Html', '.html'), ('Css', '.css')], max_length=33)),
                ('program', multiselectfield.db.fields.MultiSelectField(choices=[('Visual Studio Code', '.vscode'), ('Figma', '.figma')], max_length=24)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
