# Generated by Django 3.2.9 on 2021-11-24 21:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('.django', '.django'), ('.py', '.py'), ('.js', '.js'), ('.html', '.html'), ('.css', '.css')], max_length=26, verbose_name='Lenguajes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('.vscode', '.vscode'), ('.figma', '.figma')], max_length=14, verbose_name='Programas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
